package dev.suyash.dot.di

import android.content.Context
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import dev.suyash.dot.R
import dev.suyash.dot.core.auth.WebClientId

@Module
@InstallIn(SingletonComponent::class)
object AppModule {
    /** Generated by the google-services plugin from google-services.json (OAuth "web" client). */
    @Provides
    @WebClientId
    fun webClientId(@ApplicationContext context: Context): String = context.getString(R.string.default_web_client_id)
}
